stages:
  - build
  - push
  - deploy

build_docker_image:
  stage: build
  only:
    - main
  script:
    - /usr/bin/docker login ${CI_REGISTRY} -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}
    - /usr/bin/docker build -t ${CI_REGISTRY_IMAGE}:latest .
    - /usr/bin/docker logout ${CI_REGISTRY}

push_docker_image:
  stage: push
  only:
    - main
  script:
    - echo "start push docker image"
    - /usr/bin/docker login ${CI_REGISTRY} -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}
    - /usr/bin/docker push ${CI_REGISTRY_IMAGE}:latest
    - /usr/bin/docker logout ${CI_REGISTRY}

deploy_image:
  stage: deploy
  only:
    - main
  script:
    - ssh cluster "./deploy.sh ${CI_REGISTRY_USER} ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY_IMAGE}:latest ${PORT} ${GITLAB_USER_LOGIN}"
